/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exteam;

import bbdd.ConectorBBDD;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Eloy Murillo Granado
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    private Connection c;

    public Registro() {
        setConexion();
        initComponents();
    }

    public void setConexion() {
        ConectorBBDD bbdd = new ConectorBBDD();
        c = bbdd.getConexion();
    }

    public boolean checkFields() {
        if (jtfNombre.getText().equals("") || jtfNombre.getText().equals("Introduce tu nombre")) {
            JOptionPane.showMessageDialog(this, "Nombre vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (jtfUser.getText().equals("") || jtfUser.getText().equals("Introduce el usuario")) {
            JOptionPane.showMessageDialog(this, "Usuario vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (jtfEmail.getText().equals("") || jtfEmail.getText().equals("Introduce el correo")) {
            JOptionPane.showMessageDialog(this, "Email vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (String.valueOf(jpfPwd.getPassword()).equals("") || String.valueOf(jpfPwd.getPassword()).equals("Introduzca su contrasena")) {
            JOptionPane.showMessageDialog(this, "Contraseña vacia", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!(String.valueOf(jpfPwd.getPassword()).equals(String.valueOf(jpfPwdRepite.getPassword())))) {
            JOptionPane.showMessageDialog(this, "Las contraseñas deben coincidir", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!jrbTerms.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debes aceptar términos y condiciones", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    public boolean insert() throws SQLException {
        if (checkFields()) {
            String email = jtfEmail.getText();
            String user_password = String.valueOf(jpfPwd.getPassword());
            String player_name = jtfNombre.getText();
            String user = jtfUser.getText();

            String query = "INSERT INTO player(player_email, user_password, player_name, username, game_credit, super_pang, bubble_shooter, duck_hunt) VALUES('" + email + "', '" + user_password + "', '" + player_name + "', '" + user + "', 200, false, false, false);";
            Statement stmnt = c.createStatement();
            stmnt.executeUpdate(query);
            return true;
        } else {
            return false;
        }
    }

    int x, y;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVentana = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jtfUser = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jpfPwdRepite = new javax.swing.JPasswordField();
        jpfPwd = new javax.swing.JPasswordField();
        jrbTerms = new javax.swing.JRadioButton();
        jpBotonReg = new javax.swing.JPanel();
        jlReg = new javax.swing.JLabel();
        jpDrag = new javax.swing.JPanel();
        jpExit = new javax.swing.JPanel();
        jlExit = new javax.swing.JLabel();
        jlBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpVentana.setMaximumSize(new java.awt.Dimension(890, 560));
        jpVentana.setMinimumSize(new java.awt.Dimension(890, 560));
        jpVentana.setOpaque(false);
        jpVentana.setPreferredSize(new java.awt.Dimension(890, 560));
        jpVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jlTitle.setForeground(java.awt.Color.white);
        jlTitle.setText("Registro");
        jpVentana.add(jlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, 40));

        jtfEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jtfEmail.setText("Introduce el correo");
        jtfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEmailFocusLost(evt);
            }
        });
        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });
        jpVentana.add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 350, 30));

        jtfUser.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jtfUser.setText("Introduce el usuario");
        jtfUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfUserFocusLost(evt);
            }
        });
        jtfUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfUserMouseClicked(evt);
            }
        });
        jtfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUserActionPerformed(evt);
            }
        });
        jpVentana.add(jtfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 350, 30));

        jtfNombre.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jtfNombre.setText("Introduce tu nombre");
        jtfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNombreFocusLost(evt);
            }
        });
        jpVentana.add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 350, 30));

        jpfPwdRepite.setText("Introduzca su contrasena");
        jpfPwdRepite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpfPwdRepiteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpfPwdRepiteFocusLost(evt);
            }
        });
        jpfPwdRepite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfPwdRepiteKeyPressed(evt);
            }
        });
        jpVentana.add(jpfPwdRepite, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 350, 30));

        jpfPwd.setText("Introduzca su contrasena");
        jpfPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpfPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpfPwdFocusLost(evt);
            }
        });
        jpVentana.add(jpfPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 350, 30));

        jrbTerms.setForeground(java.awt.Color.white);
        jrbTerms.setText("Acepto terminos y servicios");
        jrbTerms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTermsActionPerformed(evt);
            }
        });
        jrbTerms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbTermsKeyPressed(evt);
            }
        });
        jpVentana.add(jrbTerms, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        jpBotonReg.setBackground(new java.awt.Color(32, 130, 196));
        jpBotonReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpBotonReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpBotonRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBotonRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpBotonRegMouseExited(evt);
            }
        });
        jpBotonReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlReg.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jlReg.setForeground(java.awt.Color.white);
        jlReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlReg.setText("Resgistrar");
        jpBotonReg.add(jlReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        jpVentana.add(jpBotonReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 240, 70));

        jpDrag.setBackground(new java.awt.Color(32, 120, 196));
        jpDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpDragMouseDragged(evt);
            }
        });
        jpDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpDragMousePressed(evt);
            }
        });
        jpDrag.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpExit.setBackground(new java.awt.Color(32, 120, 196));
        jpExit.setOpaque(false);
        jpExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpExitLayout = new javax.swing.GroupLayout(jpExit);
        jpExit.setLayout(jpExitLayout);
        jpExitLayout.setHorizontalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jpExitLayout.setVerticalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jpDrag.add(jpExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 50, 30));

        jlExit.setBackground(new java.awt.Color(32, 120, 196));
        jlExit.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jlExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExit.setText("×");
        jlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlExit.setOpaque(true);
        jlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlExitMouseExited(evt);
            }
        });
        jpDrag.add(jlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 50, 30));

        jpVentana.add(jpDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 30));

        getContentPane().add(jpVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 560));

        jlBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/exteam/backgroung.jpg"))); // NOI18N
        jlBackGround.setText("jLabel3");
        jlBackGround.setMaximumSize(new java.awt.Dimension(750, 560));
        jlBackGround.setMinimumSize(new java.awt.Dimension(750, 560));
        jlBackGround.setPreferredSize(new java.awt.Dimension(750, 560));
        getContentPane().add(jlBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpExitMouseExited
        jpExit.setBackground(new Color(32, 130, 196));
    }//GEN-LAST:event_jpExitMouseExited

    private void jpExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpExitMouseEntered
        jpExit.setBackground(new Color(248, 118, 118));
    }//GEN-LAST:event_jpExitMouseEntered

    private void jpDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDragMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jpDragMousePressed

    private void jpDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDragMouseDragged
        int x2 = evt.getXOnScreen();
        int y2 = evt.getYOnScreen();
        this.setLocation(x2 - x, y2 - y);
    }//GEN-LAST:event_jpDragMouseDragged

    private void jlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseExited
        jlExit.setBackground(new Color(32, 120, 196));
    }//GEN-LAST:event_jlExitMouseExited

    private void jlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseEntered

        jlExit.setBackground(new Color(248, 118, 118));
    }//GEN-LAST:event_jlExitMouseEntered

    private void jpBotonRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonRegMouseExited
        // TODO add your handling code here:

        jpBotonReg.setBackground(new Color(32, 130, 196));
    }//GEN-LAST:event_jpBotonRegMouseExited

    private void jpBotonRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonRegMouseEntered

        jpBotonReg.setBackground(new Color(53, 184, 230));
    }//GEN-LAST:event_jpBotonRegMouseEntered

    private void jrbTermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTermsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTermsActionPerformed

    private void jtfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUserActionPerformed

    private void jtfUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfUserMouseClicked
        // TODO add your handling code here:
        if (jtfUser.getText().equals("Introduce el usuario")) {
            jtfUser.setText("");
        }
    }//GEN-LAST:event_jtfUserMouseClicked

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseClicked
        EXteamLogin ex = new EXteamLogin();
        ex.setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jlExitMouseClicked

    private void jpBotonRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonRegMouseClicked
        try {
            if (insert()) {
                c.close();
                EXteamLogin login = new EXteamLogin();
                login.setVisible(true);
                this.setVisible(false);
                dispose();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jpBotonRegMouseClicked

    private void jpfPwdRepiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfPwdRepiteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                if (insert()) {
                    c.close();
                    EXteamLogin login = new EXteamLogin();
                    login.setVisible(true);
                    this.setVisible(false);
                    dispose();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jpfPwdRepiteKeyPressed

    private void jtfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusGained
        if (jtfNombre.getText().equals("Introduce tu nombre")) {
            jtfNombre.setText("");
        }
    }//GEN-LAST:event_jtfNombreFocusGained

    private void jtfUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfUserFocusGained
        // TODO add your handling code here:
        if (jtfUser.getText().equals("Introduce el usuario")) {
            jtfUser.setText("");
        }
    }//GEN-LAST:event_jtfUserFocusGained

    private void jtfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusGained
        // TODO add your handling code here:
        if (jtfEmail.getText().equals("Introduce el correo")) {
            jtfEmail.setText("");
        }
    }//GEN-LAST:event_jtfEmailFocusGained

    private void jpfPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpfPwdFocusGained
        // TODO add your handling code here:
        if (String.valueOf(jpfPwd.getPassword()).equals("Introduzca su contrasena")) {
            jpfPwd.setText("");
        }
    }//GEN-LAST:event_jpfPwdFocusGained

    private void jpfPwdRepiteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpfPwdRepiteFocusGained
        // TODO add your handling code here:
        if (String.valueOf(jpfPwdRepite.getPassword()).equals("Introduzca su contrasena")) {
            jpfPwdRepite.setText("");
        }
    }//GEN-LAST:event_jpfPwdRepiteFocusGained

    private void jtfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusLost
        // TODO add your handling code here:
        if (jtfNombre.getText().equals("")) {
            jtfNombre.setText("Introduce tu nombre");
        }
    }//GEN-LAST:event_jtfNombreFocusLost

    private void jtfUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfUserFocusLost
        // TODO add your handling code here:
        if (jtfUser.getText().equals("")) {
            jtfUser.setText("Introduce el usuario");
        }
    }//GEN-LAST:event_jtfUserFocusLost

    private void jtfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmailFocusLost
        // TODO add your handling code here:
        if (jtfEmail.getText().equals("")) {
            jtfEmail.setText("Introduce el correo");
        }
    }//GEN-LAST:event_jtfEmailFocusLost

    private void jpfPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpfPwdFocusLost
        // TODO add your handling code here:
        if (String.valueOf(jpfPwd.getPassword()).equals("")) {
            jpfPwd.setText("Introduzca su contrasena");
        }
    }//GEN-LAST:event_jpfPwdFocusLost

    private void jpfPwdRepiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpfPwdRepiteFocusLost
        // TODO add your handling code here:
        if (String.valueOf(jpfPwdRepite.getPassword()).equals("")) {
            jpfPwdRepite.setText("Introduzca su contrasena");
        }
    }//GEN-LAST:event_jpfPwdRepiteFocusLost

    private void jrbTermsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbTermsKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {
                if (insert()) {
                    c.close();
                    EXteamLogin login = new EXteamLogin();
                    login.setVisible(true);
                    this.setVisible(false);
                    dispose();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jrbTermsKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlBackGround;
    private javax.swing.JLabel jlExit;
    private javax.swing.JLabel jlReg;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpBotonReg;
    private javax.swing.JPanel jpDrag;
    private javax.swing.JPanel jpExit;
    private javax.swing.JPanel jpVentana;
    private javax.swing.JPasswordField jpfPwd;
    private javax.swing.JPasswordField jpfPwdRepite;
    private javax.swing.JRadioButton jrbTerms;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables
}
